# Generated by Django 5.1.1 on 2024-10-01 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('trailer_url', models.URLField()),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_3d', models.BooleanField(default=False)),
                ('age_restriction', models.PositiveSmallIntegerField(default=0)),
                ('movie_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('hall_number', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
    ]
