# Generated by Django 5.1.1 on 2024-10-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cinemahall_show_cinema_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
    ]
