# Generated by Django 5.1.1 on 2024-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinemahall_capacity_alter_show_cinema_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
