# Generated by Django 5.1.1 on 2024-10-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
