# Generated by Django 5.1.1 on 2024-10-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_show_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='show',
            name='hall_number',
        ),
        migrations.RemoveField(
            model_name='show',
            name='total_seats',
        ),
    ]
