# Generated by Django 5.1.1 on 2024-10-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_age_restriction_alter_movie_imdb_rating_and_more'),
        ('tickets', '0002_remove_ticket_is_paid_remove_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.show'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
    ]
