# Generated by Django 5.1.1 on 2024-10-02 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_booking_date_booked_remove_booking_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
