# Generated by Django 5.1.1 on 2024-10-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_show_available_seats_remove_show_hall_number_and_more'),
        ('tickets', '0006_alter_booking_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_in_tickets_app', to='cinema.show'),
        ),
    ]
